<a href="https://colab.research.google.com/github/UmarKhattab09/NLP/blob/main/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras
- One Hot Encoding

In [65]:
### Libraries USed Tensorflow> 2.0  and keras
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [66]:
#!pip install tensorflow-gpu
import tensorflow as tf
print(tf.__version__)

2.18.0


In [67]:
#Importing OneHotEncoding
from tensorflow.keras.preprocessing.text import one_hot

In [96]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']
sent
### Vocabulary size
voc_size=500
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
## 10 feature dimesnions
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

for i in range(len(embedded_docs)):
  print(embedded_docs[i])
  print(model.predict(embedded_docs[i]))

[[289, 363, 37, 238], [289, 363, 37, 123], [289, 194, 37, 467], [95, 309, 293, 386, 324], [95, 309, 293, 386, 410], [204, 289, 296, 37, 51], [451, 397, 147, 386]]
[[  0   0   0   0 289 363  37 238]
 [  0   0   0   0 289 363  37 123]
 [  0   0   0   0 289 194  37 467]
 [  0   0   0  95 309 293 386 324]
 [  0   0   0  95 309 293 386 410]
 [  0   0   0 204 289 296  37  51]
 [  0   0   0   0 451 397 147 386]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_17 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

[  0   0   0   0 289 363  37 238]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
[[-3.1545915e-02  2.5329951e-02 -2.4083102e-02  1.6684048e-03
   2.1545622e-02 -4.2533603e-02  3.7462544e-02 -8.9943409e-05
  -1.2619484e-02 -2.6080346e-02]
 [-3.1545915e-02  2.5329951e-02 -2.4083102e-02  1.6684048e-03
   2.1545622e-02 -4.2533603e-02  3.7462544e-02 -8.9943409e-05
  -1.2619484e-02 -2.6080346e-02]
 [-3.1545915e-02  2.5329951e-02 -2.4083102e-02  1.6684048e-03
   2.1545622e-02 -4.2533603e-02  3.7462544e-02 -8.9943409e-05
  -1.2619484e-02 -2.6080346e-02]
 [-3.1545915e-02  2.5329951e-02 -2.4083102e-02  1.6684048e-03
   2.1545622e-02 -4.2533603e-02  3.7462544e-02 -8.9943409e-05
  -1.2619484e-02 -2.6080346e-02]
 [ 2.3705389e-02 -4.9467683e-02 -4.1183293e-02  3.8920414e-02
   2.3250375e-02 -1.0882318e-02 -1.9140467e-03  2.2963230e-02
   4.2223122e-02  4.5279790e-02]
 [ 4.3958630e-02 -3.6542356e-02 -2.0312835e-02  4.7412802e-02
  -3.5390578e-02 -3.7594020e-02  1.1799037e-02  2.5749993e-02
   9.6731782e-03  

In [97]:

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

### Vocabulary size
voc_size=500
onehot_repr=[one_hot(words,voc_size)for words in sent]

## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

model.summary()
for i in range(len(embedded_docs)):
  print(embedded_docs[i])
  print(model.predict(embedded_docs[i]))

[[  0   0 289 281 363 293 273 177]
 [  0   0 455 319 363  20 124 121]
 [  0   0   0   0  95 103 367 410]
 [  0   0 289 166 363 467 289 426]
 [  0 105 225  21 363  20 124 121]
 [  0   0 453 363  20 124 152 153]]


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_19"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_18 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

[  0   0 289 281 363 293 273 177]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
[[ 0.04611005  0.04933618  0.04997785  0.01416632  0.00995723 -0.00419337
  -0.02238399  0.04697727 -0.03065035 -0.02430742]
 [ 0.04611005  0.04933618  0.04997785  0.01416632  0.00995723 -0.00419337
  -0.02238399  0.04697727 -0.03065035 -0.02430742]
 [-0.01852878  0.03751062  0.02583409  0.03032202  0.02473904 -0.00967396
   0.02614811 -0.03752138 -0.04423282  0.04087343]
 [ 0.02098923 -0.03537768 -0.0193064   0.01353619  0.03504654 -0.02683284
   0.00637699  0.04536502 -0.04166541 -0.04026247]
 [-0.01579692  0.02987286 -0.04168566 -0.00818088 -0.02927961  0.00659523
  -0.03660449  0.01861847 -0.02577013  0.02978753]
 [ 0.04123257  0.03365688 -0.02304976 -0.02214466 -0.04557949 -0.04302131
   0.00351294 -0.0044883   0.0162263   0.03722116]
 [ 0.04867807  0.03164244 -0.00058093 -0.01970637 -0.04000019 -0.02519187
  -0.02737453  0.0026677   0.02687627  0.03669134]
 [ 0.03623071  0.0407397   0.03501809  0.03447939 -0